// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_CONNECTION_REQUEST Message_Type = 0
	Message_HOLE_PUNCH_REQUEST Message_Type = 1
)

var Message_Type_name = map[int32]string{
	0: "CONNECTION_REQUEST",
	1: "HOLE_PUNCH_REQUEST",
}

var Message_Type_value = map[string]int32{
	"CONNECTION_REQUEST": 0,
	"HOLE_PUNCH_REQUEST": 1,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0}
}

type Message struct {
	Type                 Message_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=proto.Message_Type" json:"type,omitempty"`
	PeerID               *Message_PeerID   `protobuf:"bytes,2,opt,name=peerID,proto3" json:"peerID,omitempty"`
	PeerInfo             *Message_PeerInfo `protobuf:"bytes,3,opt,name=peerInfo,proto3" json:"peerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_CONNECTION_REQUEST
}

func (m *Message) GetPeerID() *Message_PeerID {
	if m != nil {
		return m.PeerID
	}
	return nil
}

func (m *Message) GetPeerInfo() *Message_PeerInfo {
	if m != nil {
		return m.PeerInfo
	}
	return nil
}

type Message_PeerID struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_PeerID) Reset()         { *m = Message_PeerID{} }
func (m *Message_PeerID) String() string { return proto.CompactTextString(m) }
func (*Message_PeerID) ProtoMessage()    {}
func (*Message_PeerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0}
}

func (m *Message_PeerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_PeerID.Unmarshal(m, b)
}
func (m *Message_PeerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_PeerID.Marshal(b, m, deterministic)
}
func (m *Message_PeerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_PeerID.Merge(m, src)
}
func (m *Message_PeerID) XXX_Size() int {
	return xxx_messageInfo_Message_PeerID.Size(m)
}
func (m *Message_PeerID) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_PeerID.DiscardUnknown(m)
}

var xxx_messageInfo_Message_PeerID proto.InternalMessageInfo

func (m *Message_PeerID) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type Message_PeerInfo struct {
	Info                 []byte   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_PeerInfo) Reset()         { *m = Message_PeerInfo{} }
func (m *Message_PeerInfo) String() string { return proto.CompactTextString(m) }
func (*Message_PeerInfo) ProtoMessage()    {}
func (*Message_PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 1}
}

func (m *Message_PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_PeerInfo.Unmarshal(m, b)
}
func (m *Message_PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_PeerInfo.Marshal(b, m, deterministic)
}
func (m *Message_PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_PeerInfo.Merge(m, src)
}
func (m *Message_PeerInfo) XXX_Size() int {
	return xxx_messageInfo_Message_PeerInfo.Size(m)
}
func (m *Message_PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Message_PeerInfo proto.InternalMessageInfo

func (m *Message_PeerInfo) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*Message_PeerID)(nil), "proto.Message.PeerID")
	proto.RegisterType((*Message_PeerInfo)(nil), "proto.Message.PeerInfo")
}

func init() {
	proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0)
}

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0x58, 0xc1, 0x94, 0x52, 0x07, 0x13, 0x17, 0xbb,
	0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x90, 0x3a, 0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0x30, 0x44, 0xa1, 0x1e, 0x54, 0x56, 0x2f, 0x04, 0x28, 0x15,
	0x04, 0x56, 0x20, 0xa4, 0xcb, 0xc5, 0x56, 0x90, 0x9a, 0x5a, 0xe4, 0xe9, 0x22, 0xc1, 0x04, 0x54,
	0xca, 0x6d, 0x24, 0x8a, 0xa6, 0x34, 0x00, 0x2c, 0x19, 0x04, 0x55, 0x24, 0x64, 0xcc, 0xc5, 0x01,
	0x66, 0xe5, 0xa5, 0xe5, 0x4b, 0x30, 0x83, 0x35, 0x88, 0x63, 0xd3, 0x00, 0x94, 0x0e, 0x82, 0x2b,
	0x94, 0x92, 0xe0, 0x62, 0x83, 0x18, 0x23, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x02, 0x76, 0x14, 0x4f,
	0x10, 0x90, 0x25, 0x25, 0xc7, 0xc5, 0x01, 0x53, 0x2f, 0x24, 0xc4, 0xc5, 0x92, 0x09, 0x32, 0x16,
	0x22, 0x0b, 0x66, 0x2b, 0x99, 0x71, 0xb1, 0x80, 0xdc, 0x2a, 0x24, 0xc6, 0x25, 0xe4, 0xec, 0xef,
	0xe7, 0xe7, 0xea, 0x1c, 0xe2, 0xe9, 0xef, 0x17, 0x1f, 0xe4, 0x1a, 0x18, 0xea, 0x1a, 0x1c, 0x22,
	0xc0, 0x00, 0x12, 0xf7, 0xf0, 0xf7, 0x71, 0x8d, 0x0f, 0x08, 0xf5, 0x73, 0xf6, 0x80, 0x8b, 0x33,
	0x26, 0xb1, 0x81, 0xdd, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x6f, 0x61, 0x54, 0x2a,
	0x01, 0x00, 0x00,
}
